# Generated by Django 4.0.5 on 2023-04-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_priduct_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_display_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
